// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIrfSl5grlWJ3TQxeua4-Oav2CRkC0Vg',
    appId: '1:297665808039:web:c274d7ddba6e09a0643d82',
    messagingSenderId: '297665808039',
    projectId: 'tubilearn',
    authDomain: 'tubilearn.firebaseapp.com',
    storageBucket: 'tubilearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_He-uC476b0BMY-6KtPLPhk1FfmeBq8',
    appId: '1:297665808039:android:40459b23b6b76709643d82',
    messagingSenderId: '297665808039',
    projectId: 'tubilearn',
    storageBucket: 'tubilearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCw3H4CxT4n2ATinWw02AO8DrWIBf6u3c',
    appId: '1:297665808039:ios:e3f9c390890e13f7643d82',
    messagingSenderId: '297665808039',
    projectId: 'tubilearn',
    storageBucket: 'tubilearn.firebasestorage.app',
    iosBundleId: 'com.example.tubilearnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCw3H4CxT4n2ATinWw02AO8DrWIBf6u3c',
    appId: '1:297665808039:ios:e3f9c390890e13f7643d82',
    messagingSenderId: '297665808039',
    projectId: 'tubilearn',
    storageBucket: 'tubilearn.firebasestorage.app',
    iosBundleId: 'com.example.tubilearnProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiIrfSl5grlWJ3TQxeua4-Oav2CRkC0Vg',
    appId: '1:297665808039:web:7f11cf3b2c277fa5643d82',
    messagingSenderId: '297665808039',
    projectId: 'tubilearn',
    authDomain: 'tubilearn.firebaseapp.com',
    storageBucket: 'tubilearn.firebasestorage.app',
  );
}
